version: "3.8"

services:
  one-d-music-fe:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - VITE_API_URL=http://one-d-music-node:7000/api
      - VITE_BASE_URL=http://one-d-music-node:7000
    restart: "always"
networks:
  shared-network:
    external: true