version: '3.8'

services:
  react-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"  # Host:Container
    environment:
      - VITE_API_URL=http://localhost:7000/api
      - VITE_BASE_URL=http://localhost:7000
    restart: no
