version: "3.8"

services:
  one-d-music-fe:
    container_name: one-d-music-fe
    build:
      context: .
      dockerfile: Dockerfile
      args:
        VITE_API_URL: ${VITE_API_URL}
        VITE_BASE_URL: ${VITE_BASE_URL}
    ports:
      - "3000:3000"
    networks:
      - shared-network
    env_file:
      - .env
    restart: "always"

networks:
  shared-network:
    external: true
